# Generated by Django 4.0.4 on 2022-05-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expensetype', models.CharField(max_length=40)),
                ('centrocosto', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorID', models.IntegerField()),
                ('vendorname', models.CharField(max_length=40)),
                ('docnumber', models.CharField(max_length=17)),
                ('docdate', models.DateTimeField()),
                ('docamount', models.FloatField()),
                ('doccurrency', models.CharField(max_length=4)),
                ('centrocosto', models.CharField(max_length=6)),
                ('expensetype', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Maestro_Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorID', models.IntegerField()),
                ('vendorname', models.CharField(max_length=40)),
            ],
        ),
    ]
